services:
    _defaults:
        autowire: true
        autoconfigure: true

    Eccube2\Migration\Command\:
        resource: '../src/Command/*'
        tags:
            - { name: 'console.command' }
